import {
  pgTable,
  uuid,
  varchar,
  timestamp,
  text,
  boolean,
  integer,
  jsonb,
  pgEnum,
  index,
} from 'drizzle-orm/pg-core';

/**
 * IRONFORGE — Drizzle schema.
 *
 * Phase 0: auth tables only (users, accounts, sessions, verificationTokens).
 * Phase 5: coaches, programs, stories, classSlots, trialRequests, newsletterSubs.
 *
 * Reference: Skills KB §4 (Master Execution Plan data layer sketch).
 * Reference: Skills KB §12 (Drizzle patterns from nextjs16-react19-next-auth5-drizzle-orm).
 */

// ── Auth.js v5 enums ──
export const userRoleEnum = pgEnum('user_role', ['member', 'admin']);

// ── Auth.js v5 + @auth/drizzle-adapter tables ──
export const users = pgTable(
  'users',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    name: varchar('name', { length: 80 }),
    email: varchar('email', { length: 160 }).notNull().unique(),
    emailVerified: timestamp('email_verified', { withTimezone: true }),
    image: varchar('image', { length: 500 }),
    passwordHash: varchar('password_hash', { length: 100 }), // bcrypt — null for OAuth-only users
    role: userRoleEnum('role').notNull().default('member'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({ emailIdx: index('users_email_idx').on(t.email) }),
);

export const accounts = pgTable(
  'accounts',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    type: varchar('type', { length: 40 }).notNull(),
    provider: varchar('provider', { length: 40 }).notNull(),
    providerAccountId: varchar('provider_account_id', { length: 100 }).notNull(),
    refresh_token: text('refresh_token'),
    access_token: text('access_token'),
    expires_at: integer('expires_at'),
    token_type: varchar('token_type', { length: 40 }),
    scope: varchar('scope', { length: 200 }),
    id_token: text('id_token'),
    session_state: varchar('session_state', { length: 200 }),
  },
  (t) => ({
    providerIdx: index('accounts_provider_idx').on(t.provider, t.providerAccountId),
    userIdx: index('accounts_user_idx').on(t.userId),
  }),
);

export const sessions = pgTable(
  'sessions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    sessionToken: varchar('session_token', { length: 100 }).notNull().unique(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    expires: timestamp('expires', { withTimezone: true }).notNull(),
  },
  (t) => ({ userIdx: index('sessions_user_idx').on(t.userId) }),
);

export const verificationTokens = pgTable(
  'verification_tokens',
  {
    identifier: varchar('identifier', { length: 160 }).notNull(),
    token: varchar('token', { length: 100 }).notNull().unique(),
    expires: timestamp('expires', { withTimezone: true }).notNull(),
  },
  (t) => ({ identifierIdx: index('vt_identifier_idx').on(t.identifier) }),
);

// ──────────────────────────────────────────────────────────────────────
// Phase 5 tables (declared now so the schema barrel is stable).
// Migrations are generated by `pnpm drizzle:generate` once Phase 5 lands.
// ──────────────────────────────────────────────────────────────────────

export const coaches = pgTable(
  'coaches',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    slug: varchar('slug', { length: 80 }).notNull().unique(),
    name: varchar('name', { length: 80 }).notNull(),
    title: varchar('title', { length: 120 }).notNull(),
    bio: text('bio').notNull(),
    certifications: text('certifications').array(),
    specialties: text('specialties').array(),
    signatureWorkout: varchar('signature_workout', { length: 120 }),
    portraitKey: varchar('portrait_key', { length: 200 }),
    yearsExp: integer('years_exp'),
    order: integer('order').default(0).notNull(),
    published: boolean('published').default(false).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({ slugIdx: index('coaches_slug_idx').on(t.slug) }),
);

export const programs = pgTable(
  'programs',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    slug: varchar('slug', { length: 80 }).notNull().unique(),
    goal: varchar('goal', { length: 40 }).notNull(),
    title: varchar('title', { length: 120 }).notNull(),
    subtitle: varchar('subtitle', { length: 200 }),
    description: text('description').notNull(),
    duration: varchar('duration', { length: 40 }),
    sessionsPerWeek: integer('sessions_per_week'),
    intensity: varchar('intensity', { length: 20 }),
    heroKey: varchar('hero_key', { length: 200 }),
    priceCents: integer('price_cents'),
    stripePriceId: varchar('stripe_price_id', { length: 80 }),
    coachId: uuid('coach_id').references(() => coaches.id),
    order: integer('order').default(0).notNull(),
    published: boolean('published').default(false).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({ goalIdx: index('programs_goal_idx').on(t.goal) }),
);

export const stories = pgTable('stories', {
  id: uuid('id').primaryKey().defaultRandom(),
  slug: varchar('slug', { length: 80 }).notNull().unique(),
  memberName: varchar('member_name', { length: 80 }).notNull(),
  memberAge: integer('member_age'),
  programSlug: varchar('program_slug', { length: 80 }),
  weeks: integer('weeks'),
  beforeKey: varchar('before_key', { length: 200 }),
  afterKey: varchar('after_key', { length: 200 }),
  quote: text('quote').notNull(),
  timeline: jsonb('timeline'),
  videoKey: varchar('video_key', { length: 200 }),
  published: boolean('published').default(false).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const classSlots = pgTable(
  'class_slots',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    programId: uuid('program_id').references(() => programs.id),
    coachId: uuid('coach_id').references(() => coaches.id),
    startsAt: timestamp('starts_at', { withTimezone: true }).notNull(),
    durationMin: integer('duration_min').default(60),
    capacity: integer('capacity').default(8),
    location: varchar('location', { length: 120 }).default('47 Eastbound Alley, NYC'),
  },
  (t) => ({ startsAtIdx: index('class_slots_starts_at_idx').on(t.startsAt) }),
);

export const trialRequests = pgTable(
  'trial_requests',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    name: varchar('name', { length: 80 }).notNull(),
    email: varchar('email', { length: 160 }).notNull(),
    phone: varchar('phone', { length: 40 }),
    goal: varchar('goal', { length: 40 }).notNull(),
    preferredTime: varchar('preferred_time', { length: 20 }).notNull(),
    preferredCoachId: uuid('preferred_coach_id').references(() => coaches.id),
    notes: text('notes'),
    status: varchar('status', { length: 20 }).default('received'),
    idempotencyKey: varchar('idempotency_key', { length: 60 }).notNull().unique(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({ createdIdx: index('trial_requests_created_idx').on(t.createdAt) }),
);

export const newsletterSubs = pgTable(
  'newsletter_subs',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    email: varchar('email', { length: 160 }).notNull().unique(),
    consentAt: timestamp('consent_at', { withTimezone: true }).defaultNow().notNull(),
    source: varchar('source', { length: 40 }).default('site_footer'),
  },
);

// ── Subscriptions (Stripe membership billing) ──
export const subscriptionStatusEnum = pgEnum('subscription_status', [
  'active',
  'past_due',
  'canceled',
  'incomplete',
  'trialing',
]);

export const subscriptions = pgTable(
  'subscriptions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    stripeCustomerId: varchar('stripe_customer_id', { length: 100 }).notNull(),
    stripeSubscriptionId: varchar('stripe_subscription_id', { length: 100 }).notNull().unique(),
    stripePriceId: varchar('stripe_price_id', { length: 100 }).notNull(),
    tier: varchar('tier', { length: 40 }).notNull(), // 'forge' | 'forge_plus' | 'forge_private'
    status: subscriptionStatusEnum('status').notNull().default('active'),
    currentPeriodEnd: timestamp('current_period_end', { withTimezone: true }),
    cancelAtPeriodEnd: boolean('cancel_at_period_end').default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    customerIdx: index('subscriptions_customer_idx').on(t.stripeCustomerId),
    userIdx: index('subscriptions_user_idx').on(t.userId),
  }),
);

// ── Type exports (used across features) ──
export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Coach = typeof coaches.$inferSelect;
export type NewCoach = typeof coaches.$inferInsert;
export type Program = typeof programs.$inferSelect;
export type NewProgram = typeof programs.$inferInsert;
export type Story = typeof stories.$inferSelect;
export type NewStory = typeof stories.$inferInsert;
export type ClassSlot = typeof classSlots.$inferSelect;
export type TrialRequest = typeof trialRequests.$inferSelect;
export type NewsletterSub = typeof newsletterSubs.$inferSelect;
export type Subscription = typeof subscriptions.$inferSelect;
export type NewSubscription = typeof subscriptions.$inferInsert;
